// Contract test: the synchronous `SKILLS` mirror + game constants in
// `skills.ts` must match the engine byte-for-byte. The fixture is generated by
// the Rust test `tauri_wrapper::tests::emit_skill_metadata_fixture` from the
// engine's canonical `skill_metadata()` / `game_constants_cmd()` output. If the
// engine's skill table changes, regenerate the fixture (`cargo test -p
// tauri_wrapper emit_skill_metadata_fixture`) and this test guards the TS side.

import { describe, it, expect } from "vitest";
import fixture from "./__fixtures__/skill-metadata.json";
import {
  SKILLS,
  SKILL_COUNT,
  SKILL_BLAST,
  SKILL_SHOVE,
  focusSplitKind,
  MODIFIER_FOCUS,
  MODIFIER_CHARGE,
  MODIFIER_MOVE_ATTACK_USED,
  PHASE_MOVE,
  PHASE_SKILL,
  PHASE_DRAFT,
  PLAYER_P1,
  PLAYER_P2,
  GAME_ONGOING,
  GAME_P1_WINS,
  GAME_P2_WINS,
} from "./skills";

describe("skills contract (TS mirror ↔ engine)", () => {
  it("SKILLS matches the engine skill table for every id", () => {
    expect(fixture.skills).toHaveLength(SKILL_COUNT);
    for (const eng of fixture.skills) {
      const ts = SKILLS[eng.id];
      expect(ts, `SKILLS[${eng.id}] (${eng.key}) missing`).toBeDefined();
      expect(ts).toMatchObject({
        id: eng.id,
        key: eng.key,
        category: eng.category,
        cost: eng.cost,
        defaultRange: eng.defaultRange,
        targetOwner: eng.targetOwner,
        hasFocusModeChoice: eng.hasFocusModeChoice,
        needsDirectionPick: eng.needsDirectionPick,
      });
    }
    // No extra ids on the TS side.
    expect(Object.keys(SKILLS).map(Number).sort((a, b) => a - b)).toEqual(
      fixture.skills.map((s) => s.id).sort((a, b) => a - b),
    );
  });

  it("named skill ids resolve to the engine's focus/direction skills", () => {
    const blast = fixture.skills.find((s) => s.key === "blast")!;
    const shove = fixture.skills.find((s) => s.key === "shove")!;
    expect(SKILL_BLAST).toBe(blast.id);
    expect(SKILL_SHOVE).toBe(shove.id);
    expect(blast.hasFocusModeChoice).toBe(true);
    expect(shove.needsDirectionPick).toBe(true);
  });

  it("game constants match the engine encoding", () => {
    const c = fixture.constants;
    expect(PHASE_MOVE).toBe(c.phaseMove);
    expect(PHASE_SKILL).toBe(c.phaseSkill);
    expect(PHASE_DRAFT).toBe(c.phaseDraft);
    expect(MODIFIER_FOCUS).toBe(c.modifierFocus);
    expect(MODIFIER_CHARGE).toBe(c.modifierCharge);
    expect(MODIFIER_MOVE_ATTACK_USED).toBe(c.modifierMoveAttackUsed);
    expect(PLAYER_P1).toBe(c.playerP1);
    expect(PLAYER_P2).toBe(c.playerP2);
    expect(GAME_ONGOING).toBe(c.gameOngoing);
    expect(GAME_P1_WINS).toBe(c.gameP1Wins);
    expect(GAME_P2_WINS).toBe(c.gameP2Wins);
    expect(SKILL_COUNT).toBe(c.skillCount);
  });

  it("focusSplitKind classifies wheel focus-splits by skill type", () => {
    // Blast/Shove split into activation(+rng)/effect(+eff).
    expect(focusSplitKind(SKILLS[10].id)).toBe("focusMode"); // blast
    expect(focusSplitKind(SKILLS[11].id)).toBe("focusMode"); // shove
    // Shield/Dash/Retreat split into self/ally under Focus.
    expect(focusSplitKind(SKILLS[6].id)).toBe("retarget");  // shield
    expect(focusSplitKind(SKILLS[9].id)).toBe("retarget");  // dash
    expect(focusSplitKind(SKILLS[13].id)).toBe("retarget"); // retreat
    // Everything else has no wheel split.
    for (const id of [1, 2, 3, 4, 5, 7, 8, 12, 14, 15]) {
      expect(focusSplitKind(id), `skill ${id} (${SKILLS[id].key})`).toBeNull();
    }
    expect(focusSplitKind(999)).toBeNull();
  });
});
