#import "../shared/template.typ": *
#import "../shared/baseline-sections.typ": *
#show: template.with(title: "(GAME NAME) — Baseline Rules")

= (GAME NAME) — Baseline Rules

_Version: 2026-04-25. Source of truth for all test scenario rule sheets._\
_Do not edit this file during a playtest — use the layer-specific rule sheet instead._

#section-goal()
#section-components()
#section-setup()
#section-round-structure()
#section-turn-structure()
#section-movement-phase()
#section-standard-attack()
#section-action-phase()
#section-skill-system()
#section-resource-economy()
#section-health-armor()
#section-bodyguard()
#section-skill-drafting()
#section-progression()

#pagebreak()

#section-skill-reference()
#section-quick-reference()
